### ISSUE TITLE
SDK Auth/Web3 Auth: Approve token is broken

### ISSUE THREAD

**Issue by skuhlmann** [odyssy-automaton/moloch-pokemol#7]
Error: Approving weth: TypeError: this.sdkSubmit is not a function

TokenService.js Line 64

**Comment by rhlsthrm** [comment]
Fixed this for Web3 will look into for SDK...

**Comment by skuhlmann** [comment]
Seeing this on the SDK side and we're working on it.

**Comment by dekanbro** [comment]
fixed in PR #21
