### ISSUE TITLE
Web3 Auth: User Shares aren't showing in account page.

### ISSUE THREAD

**Issue by skuhlmann** [odyssy-automaton/moloch-pokemol#8]

**Comment by rhlsthrm** [comment]
Shares are showing up for me in the account page, how are you reproducing this?

<img width="1657" alt="image" src="https://user-images.githubusercontent.com/11512787/71415059-4d0f9380-265a-11ea-9251-8b989af6d41f.png">

**Comment by skuhlmann** [comment]
Yeah I'm seeing shares now too. Ven and I both saw the issue last week, I think we must have had delegate keys pointing at the wrong address as we switch between web3 and SDK.

Closing.
